# Project information
site_name: 빅데이터 엣지 클라우드 서비스 연구센터
site_url: http://becs.kaist.ac.kr/becs
site_author: BECS Research Center
site_description: >-
  Official website of BECS ITRC Research Center, South Korea.

# Copyright
copyright: Copyright &copy; 2020 BECS Research Center

# Configuration
theme:
  name: null
  custom_dir: material

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: false

  # Default values, taken from mkdocs_theme.yml
  language: kr
  features:
    - navigation.tabs: false
  palette:
    scheme: default
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png

# Page tree
# nav:
#   - Home: index.md

extra_css:
  - stylesheets/extra.css
